name: Publish

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - dev
  #     - main
  push:
    branches: 
      - main

jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://npm.pkg.github.com/

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        npx lerna version --conventional-commits --yes

        npx lerna publish from-git --yes --registry https://npm.pkg.github.com
