name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - main
  # push:
  #   branches: 
  #     - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: "Use NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://npm.pkg.github.com/

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        
        if [ ${{ github.base_ref }} = main ]; then
          git commit --allow-empty -m "CI Test"
          git push origin main
          git switch dev
          git merge main
          git push origin dev
        fi
